=== openclonk/openclonk/docs/clonk.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY % text "a | img | emlink | funclink | em | code | strong">

<!ELEMENT funcs (func+, (author, date)+)>
  <!ELEMENT func           (title, deprecated?, category, subcat*, version, deprecated?, syntax, desc, remark*, examples?, related?)>
    <!ELEMENT title        (#PCDATA)>
    <!ELEMENT category     (#PCDATA)>
    <!ELEMENT subcat       (#PCDATA)>
    <!ELEMENT version      (#PCDATA | extversion)*>
      <!ELEMENT extversion (#PCDATA)>
    <!ELEMENT deprecated   EMPTY>
    <!ELEMENT internal     EMPTY>
    <!ELEMENT syntax       (rtype, params*)>
      <!ELEMENT rtype      (#PCDATA)>
      <!ELEMENT params     (#PCDATA | param)*>
        <!ELEMENT param    (type?, optional?, name, optional?, desc, optional?)>
          <!ELEMENT name   (#PCDATA)>
          <!ELEMENT type   (#PCDATA)>
          <!ELEMENT desc   (#PCDATA | br | ul | li | table | %text;)*>
          <!ELEMENT optional EMPTY>
    <!ELEMENT remark       (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT examples     (example+)>
      <!ELEMENT example    (code | text)*>
        <!ELEMENT code     (#PCDATA | funclink | emlink | em | strong)*>
        <!ELEMENT text     (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT related      (funclink | emlink)+>
      <!ELEMENT funclink   (#PCDATA)>
      <!ELEMENT emlink     (#PCDATA)>
        <!ATTLIST emlink href CDATA #REQUIRED>
  <!ELEMENT author         (#PCDATA)>
  <!ELEMENT date           (#PCDATA)>
<!ELEMENT doc (title, (h | text | dl | part | code | author | date | img)*)>
  <!ELEMENT part (h | text | part | code | dl)*>

<!ELEMENT br EMPTY>

<!ELEMENT table (#PCDATA | caption | rowh | row | bitmask)*>
  <!ELEMENT caption (#PCDATA)>
    <!ATTLIST caption
      id ID #IMPLIED>
  <!ELEMENT row   (#PCDATA | col)*>
    <!ATTLIST row
      id ID #IMPLIED>
  <!ELEMENT rowh  (#PCDATA | col)*>
  <!ELEMENT col   (#PCDATA | %text;)*>
    <!ATTLIST col
      colspan CDATA #IMPLIED>
  <!ELEMENT bitmask (#PCDATA)>

<!ELEMENT ul    (#PCDATA | li)*>
  <!ELEMENT li    (#PCDATA | br | %text;)*>

<!ELEMENT dl    (#PCDATA | dd | dt)*>
  <!ELEMENT dt    (#PCDATA | br | %text;)*>
    <!ATTLIST dt
      id ID #IMPLIED>
  <!ELEMENT dd    (#PCDATA | text | code)*>

<!ELEMENT em    (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

<!ELEMENT h     (#PCDATA)>
  <!ATTLIST h
    id ID #IMPLIED>

<!ELEMENT img   EMPTY>
  <!ATTLIST img
    src CDATA #REQUIRED
    width CDATA "0"
    height CDATA "0"
    id ID #IMPLIED>

<!ELEMENT a     (#PCDATA)>
  <!ATTLIST a
    href CDATA #REQUIRED>

=== openclonk/openclonk/docs/sdk/script/fn/SetVisibility.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
	<func>
		<title>SetVisibility</title>
		<category>Objekte</category><subcat>Sichtbarkeit</subcat>
		<version>4.9.1.0 GWE</version>
		<syntax>
			<rtype>bool</rtype>
			<params>
				<param><type>int</type><name>dwVisibility</name>
					<desc>
						Bitmaske, die die neue Sichtbarkeit angibt.<br />
						Entweder <funclink>VIS_All</funclink> oder <funclink>VIS_None</funclink>, oder eine Bitmaske aus <funclink>VIS_Owner</funclink>, <funclink>VIS_Allies</funclink>, <funclink>VIS_Enemies</funclink>, <funclink>VIS_God</funclink> und <funclink>VIS_Local</funclink>.
					</desc>
				</param>
				<param><type>object</type><name>obj</name><desc>Objekt, dessen Sichtbarkeit geändert werden soll. 0 bei lokalem Aufruf.</desc><optional /></param>
			</params>
		</syntax>
		<desc>
			Verändert die Sichtbarkeit eines Objekts. Objekte können für beliebige Gruppen sichtbar gemacht werden, indem für dwVisibility eine Bitmaske angegeben wird.
		</desc>
		<examples>
			<example>
				<code>SetVisibility(<funclink>VIS_None</funclink>(), <funclink>GetCursor</funclink>())</code>
				<text>Macht den ausgewählten Clonk von Spieler 0 völlig unsichtbar.</text>
			</example>
			<example>
				<code>SetVisibility(<funclink>VIS_Owner</funclink>() | <funclink>VIS_Allies</funclink>(), <funclink>GetCursor</funclink>())</code>
				<text>Macht den ausgewählten Clonk von Spieler 0 nur für sich und Verbündete sichtbar.</text>
			</example>
		</examples>
		<related>
			<funclink>GetVisibility</funclink>
			<funclink>CheckVisibility</funclink>
			<funclink>VIS_All</funclink>
			<funclink>VIS_None</funclink>
			<funclink>VIS_Owner</funclink>
			<funclink>VIS_Allies</funclink>
			<funclink>VIS_Enemies</funclink>
			<funclink>VIS_God</funclink>
			<funclink>VIS_Local</funclink>
		</related>
	</func>
	<author>Sven2</author><date>November 2001</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/GetYDir.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>GetYDir</title>
    <category>Objects</category>
    <subcat>Movement</subcat>
    <version>1.0 OC</version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>int</type>
          <name>precision</name>
          <desc>Precision with which to retrieve the speed. Default value is 10.</desc>
        </param>
      </params>
    </syntax>
    <desc>Returns the vertical speed of the calling object.</desc>
    <remark>The function will return the speed in pixels per frame multiplied with precision. If no precision is specified, the ten-fold speed value will be returned.</remark>
    <related>
      <funclink>GetXDir</funclink>
      <funclink>SetXDir</funclink>
      <funclink>SetYDir</funclink>
      <funclink>GetX</funclink>
      <funclink>GetY</funclink>
      <funclink>SetPosition</funclink>
    </related>
  </func>
  <author>Cucaracha</author><date>2002-05</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/GetCrew.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>GetCrew</title>
    <category>Objects</category>
    <subcat>Crew</subcat>
    <version>1.0 OC<extversion>9.0 OC</extversion></version>
    <syntax>
      <rtype>object</rtype>
      <params>
        <param>
          <type>int</type>
          <name>index</name>
          <desc>Crew index of the clonk.</desc>
        </param>
      </params>
    </syntax>
    <desc>Returns the indicated crew member of a player. For an invalid index <code>nil</code> is returned.</desc>
    <remark>Prior to 9.0 OC this function existed as a global function with the player number as an additional first parameter.</remark>
    <examples>
      <example>
        <code><funclink>GetPlayer</funclink>(0)-&gt;GetCrew()-&gt;<funclink>CreateContents</funclink>(Shovel)</code>
        <text>Gives a shovel to the first clonk of the first player.</text>
        <code>var i=<funclink>GetCrewCount</funclink>(0); <funclink>while</funclink> (i--) <funclink>Kill</funclink>(GetCrew(0, i));</code>
        <text>Kills all crew members of the first player.</text>
      </example>
    </examples>
    <related>
      <funclink>GetCrewCount</funclink>
      <funclink>GetHiRank</funclink>
      <funclink>GetCursor</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2002-05</date>
  <author>Marky</author><date>2020-06</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/GetPlayerByIndex.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
        <func>
                <title>GetPlayerByIndex</title>
                <category>Spieler</category>
                <version>4.9.1.0 GWE<extversion>4.9.6.0 CR</extversion></version>
                <syntax>
                        <rtype>int</rtype>
			<params>
				<param><type>int</type><name>iIndex</name><desc>Index in der Spielerliste</desc></param>
				<param><type>int</type><name>ePlayerType</name><desc>Wenn angegeben, wird der indizierte Spieler des angegebenen Typs zurückgegeben. So lassen sich zum Beispiel nur alle menschlichen oder nur alle Scriptspieler durchgehen. Für eine Liste gültiger Werte, siehe <funclink>GetPlayerType</funclink>.</desc><optional /></param>
			</params>
                </syntax>
                <desc>Gibt die indizierte Spielernummer zurück. Die Funktion garantiert für Werte zwischen 0 und GetPlayerCount()-1, dass eine gültige Spielernummer zurückgegeben wird (denn durch eliminierte Spieler und Neubeitritte kann es vorkommen, dass "Löcher" unbelegter Spielernummern in der Liste entstehen!). Damit ist es einfacher, eine Schleife zu schreiben, die alle Spielernummern durchgeht. Ab 4.9.6.0 CR.</desc>
                <examples>
                        <example>
<code><funclink>for</funclink>(var i = 0; i &lt; <funclink>GetPlayerCount</funclink>(); i++)
  <funclink>Log</funclink>("Moin, %s", <funclink>GetPlayerName</funclink>(GetPlayerByIndex(i)));</code>
                                <text>Begrüßt alle Spieler im Log.</text>
                        </example>
                        <example>
<code><funclink>for</funclink>(var i = 0; i &lt; <funclink>GetPlayerCount</funclink>(C4PT_User); i++)
  <funclink>EliminatePlayer</funclink>(GetPlayerByIndex(i, C4PT_User));</code>
                                <text>Eliminiert alle regulären Spieler, aber lässt Scriptspieler am Leben.</text>
                        </example>

                </examples>
                <related>
                        <funclink>GetPlayerByName</funclink>
                        <funclink>GetPlayerName</funclink>
                        <funclink>GetPlayerCount</funclink>
                        <funclink>GetPlayerType</funclink>
                </related>
        </func>
        <author>Sven2</author><date>Dezember 2007</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/Contents.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>Contents</title>
    <category>Objects</category>
    <subcat>Contents</subcat>
    <version>1.0 OC</version>
    <syntax>
      <rtype>object</rtype>
      <params>
        <param>
          <type>int</type>
          <name>index</name>
          <desc>Index of the object in the container, starting with 0.</desc>
        </param>
      </params>
    </syntax>
    <desc>Returns the indicated object contained in the target obj.</desc>
    <related>
      <funclink>Contained</funclink>
      <funclink>FindContents</funclink>
    </related>
  </func>
  <author>springer</author><date>2002-04</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/CanInsertMaterial.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>CanInsertMaterial</title>
    <category>Landscape</category>
    <subcat>Material</subcat>
    <version>5.4 OC</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>int</type>
          <name>material_index</name>
          <desc>Material to test to be inserted (see <funclink>Material</funclink>()).</desc>
        </param>
        <param>
          <type>int</type>
          <name>x</name>
          <desc>X insert position or offset</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>y</name>
          <desc>Y insert position or offset</desc>
          <optional />
        </param>
        <param>
          <type>proplist</type>
          <name>out_insertpos</name>
          <desc>If a writeable proplist is passed, members x and y are filled with the position at which the material would be inserted.</desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>Tests if a material pixel at the given position can be inserted.</desc>
    <remark>If the target position already contains material of the same density as the inserted material, the engine will search upwards for a proper insertion position.</remark>
    <related>
      <funclink>Material</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2001-11</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/OCF_Available.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <const>
    <title>OCF_Available</title>
    <category>Objects</category>
    <subcat>OCF</subcat>
    <version>1.0 OC</version>
    <syntax><rtype>int</rtype></syntax>
    <desc>Object character flag: this object can theoretically be acquired by a clonk, meaning it is either uncontained or in a container to which the clonk can have access.</desc>
    <remark>For more information and examples regarding these constants see <emlink href="definition/ocf.html">object character flags</emlink>.</remark>
    <related>
      <funclink>GetOCF</funclink>
      <funclink>FindObject</funclink>
      <emlink href="definition/ocf.html">Object character flags</emlink>
    </related>
  </const>
  <author>Sven2</author><date>2002-05</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/Bubble.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>Bubble</title>
    <category>Umwelt</category><subcat>Effekte</subcat>
    <version>4.6.5.0 CP</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param><type>int</type><name>x</name><desc>X-Position der Luftblase. Offset bei lokalem Aufruf.</desc><optional /></param>
        <param><type>int</type><name>y</name><desc>Y-Position der Luftblase. Offset bei lokalem Aufruf.</desc><optional /></param>
      </params>
    </syntax>
    <desc>Erzeugt eine Luftblase.</desc>
    <remark>Die maximale Anzahl der Luftblasen auf dem Spielfeld richtet sich nach der Einstellung für Rauchentwicklung in den Optionen. Im Netzwerk und bei Aufnahmen/Wiedergaben ist dieser Wert immer 150.</remark>
    <examples>
      <example>
        <code>Bubble();</code>
        <text>Erzeugt eine Luftblase beim aufrufenden Objekt.</text>
      </example>
    </examples>
  </func>
  <author>Sven2</author><date>November 2001</date>
</funcs>
