=== openclonk/openclonk/docs/clonk.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY % text "a | img | emlink | funclink | em | code | strong">

<!ELEMENT funcs (func+, (author, date)+)>
  <!ELEMENT func           (title, deprecated?, category, subcat*, version, deprecated?, syntax, desc, remark*, examples?, related?)>
    <!ELEMENT title        (#PCDATA)>
    <!ELEMENT category     (#PCDATA)>
    <!ELEMENT subcat       (#PCDATA)>
    <!ELEMENT version      (#PCDATA | extversion)*>
      <!ELEMENT extversion (#PCDATA)>
    <!ELEMENT deprecated   EMPTY>
    <!ELEMENT internal     EMPTY>
    <!ELEMENT syntax       (rtype, params*)>
      <!ELEMENT rtype      (#PCDATA)>
      <!ELEMENT params     (#PCDATA | param)*>
        <!ELEMENT param    (type?, optional?, name, optional?, desc, optional?)>
          <!ELEMENT name   (#PCDATA)>
          <!ELEMENT type   (#PCDATA)>
          <!ELEMENT desc   (#PCDATA | br | ul | li | table | %text;)*>
          <!ELEMENT optional EMPTY>
    <!ELEMENT remark       (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT examples     (example+)>
      <!ELEMENT example    (code | text)*>
        <!ELEMENT code     (#PCDATA | funclink | emlink | em | strong)*>
        <!ELEMENT text     (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT related      (funclink | emlink)+>
      <!ELEMENT funclink   (#PCDATA)>
      <!ELEMENT emlink     (#PCDATA)>
        <!ATTLIST emlink href CDATA #REQUIRED>
  <!ELEMENT author         (#PCDATA)>
  <!ELEMENT date           (#PCDATA)>
<!ELEMENT doc (title, (h | text | dl | part | code | author | date | img)*)>
  <!ELEMENT part (h | text | part | code | dl)*>

<!ELEMENT br EMPTY>

<!ELEMENT table (#PCDATA | caption | rowh | row | bitmask)*>
  <!ELEMENT caption (#PCDATA)>
    <!ATTLIST caption
      id ID #IMPLIED>
  <!ELEMENT row   (#PCDATA | col)*>
    <!ATTLIST row
      id ID #IMPLIED>
  <!ELEMENT rowh  (#PCDATA | col)*>
  <!ELEMENT col   (#PCDATA | %text;)*>
    <!ATTLIST col
      colspan CDATA #IMPLIED>
  <!ELEMENT bitmask (#PCDATA)>

<!ELEMENT ul    (#PCDATA | li)*>
  <!ELEMENT li    (#PCDATA | br | %text;)*>

<!ELEMENT dl    (#PCDATA | dd | dt)*>
  <!ELEMENT dt    (#PCDATA | br | %text;)*>
    <!ATTLIST dt
      id ID #IMPLIED>
  <!ELEMENT dd    (#PCDATA | text | code)*>

<!ELEMENT em    (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

<!ELEMENT h     (#PCDATA)>
  <!ATTLIST h
    id ID #IMPLIED>

<!ELEMENT img   EMPTY>
  <!ATTLIST img
    src CDATA #REQUIRED
    width CDATA "0"
    height CDATA "0"
    id ID #IMPLIED>

<!ELEMENT a     (#PCDATA)>
  <!ATTLIST a
    href CDATA #REQUIRED>

=== openclonk/openclonk/docs/sdk/scenario/basefunc.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE doc SYSTEM "../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../clonk.xsl"?>
<doc>
<title>Basisfunktionalitäten</title>
<h id="BaseFunc">Basisfunktionalitäten</h>
<text>Die BaseFunctionality-Option (DWord-Bitmaske) eines Szenarios bestimmt, welche Funktionen eine Basis (Gebäude mit Spielerflagge) in einem Szenario erfüllen kann.</text>
<text>
<table><rowh>
	<col>Bit</col><col>Wert</col><col>BaseFunctionality</col><col>Beschreibung</col>
</rowh><row>
	<col>0</col><col>1</col><col>BASEFUNC_AutoSellContents</col><col>Loren werden ausgeleert und Gold wird aus der Basis und direkt enthaltenen Objekten verkauft.</col>
</row><row>
	<col>1</col><col>2</col><col>BASEFUNC_RegenerateEnergy</col><col>Verbündete Clonks regenerieren in der Basis Energie.</col>
</row><row>
	<col>2</col><col>4</col><col>BASEFUNC_Buy</col><col>Objekte können in der Basis gekauft werden.</col>
</row><row>
	<col>3</col><col>8</col><col>BASEFUNC_Sell</col><col>Objekte können in der Basis verkauft werden.</col>
</row><row>
	<col>4</col><col>16</col><col>BASEFUNC_RejectEntrance</col><col>Gegnerischen Clonks wird das Öffnen des Eingangs verwehrt.</col>
</row><row>
	<col>5</col><col>32</col><col>BASEFUNC_Extinguish</col><col>Clonks werden in der Basis gelöscht.</col>
</row><row>
	<col>1-16</col><col>65536</col><col>BASEFUNC_Default</col><col>Alle Bits gesetzt: Standardverhalten für Basis.</col>
</row>
</table>
</text>
<author>Sven2</author><date>März 2006</date>
</doc>

=== openclonk/openclonk/docs/sdk/script/fn/RemoveObject.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
	<func>
		<title>RemoveObject</title>
		<category>Objekte</category><subcat>Existenz</subcat>
		<version>4.6.5.0 CP<extversion>4.9.1.0 GWE</extversion></version>
		<syntax>
			<rtype>void</rtype>
			<params>
				<param><type>bool</type><name>fEjectContents</name><desc>Wenn wahr, wird der Inhalt des Objekts vor der Vernichtung ausgeleert. Ansonsten wird er mit vernichtet.</desc><optional /></param>
			</params>
		</syntax>
		<desc>Entfernt das aufrufende Objekt.</desc>
		<remark>
			Beim Löschen eines Objekts werden viele interne Zeiger gelöscht, und das Objekt selber wird ungültig. Darum sollte der Zeiger auf dieses Objekt (z.B. innerhalb von threadlokalen Variablen) anschließend nicht mehr benutzt werden. Wenn sich ein Objekt selber entfernt, sollte die Funktion sofort mit return() beendet werden.<br />
			Wenn sich das Objekt zu diesem Zeitpunkt in einer Crew befindet, wird das assoziierte Infoobjekt in der Crew nicht als getötet markiert. Das heißt, ein darauffolgender <funclink>MakeCrewMember</funclink>()-Aufruf kann wieder in demselben Mannschaftsmitglied resultieren. Um dies zu verhindern, sollte das Objekt zuvor mit <funclink>Kill</funclink>() getötet werden.
		</remark>
		<examples>
			<example>
				<code>public func Activate(pClonk) { pClonk->RemoveObject(); }</code>
				<text>Wenn ein Clonk dieses Objekt aktiviert, wird er entfernt.</text>
			</example>
		</examples>
		<related>
			<funclink>Explode</funclink>
			<funclink>CreateObject</funclink>
			<funclink>Kill</funclink>
		</related>
	</func>
	<author>Sven2</author><date>August 2002</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/Sort_Random.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>Sort_Random</title>
    <category>Objects</category>
    <subcat>Search</subcat>
    <version>1.0 OC</version>
    <syntax><rtype>array</rtype></syntax>
    <desc>Sort criterion: Sorts the found objects randomly.</desc>
    <remark>Sort_Random should not be used together with <funclink>FindObject</funclink> to find a random, matching object. Instead the first object of a <funclink>FindObjects</funclink> search with a SortRandom parameter can be used for instance.</remark>
    <remark>For additional information on the use of this function see <funclink>FindObjects</funclink>.</remark>
    <related><funclink>FindObjects</funclink></related>
  </func>
  <author>Newton</author><date>2009-07</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/C4D_All.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <const>
    <title>C4D_All</title>
    <category>Objects</category>
    <subcat>Category</subcat>
    <version>1.0 OC</version>
    <syntax><rtype>int</rtype></syntax>
    <desc>Object category: all categories.</desc>
    <related>
      <funclink>GetCategory</funclink>
      <funclink>SetCategory</funclink>
    </related>
  </const>
  <author>Sven2</author><date>2002-01</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/EffectCall.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>EffectCall</title>
    <category>Effekte</category>
    <version>4.9.5.0 CE</version>
    <syntax>
      <rtype>any</rtype>
      <params>
        <param>
          <type>object</type>
          <name>target</name>
          <desc>Zielobjekt des Effektes, auf dessen Variablenspeicher zugegriffen wird. 0 für globale Effekte.</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>number</name>
          <desc>Effektnummer. Effektnummern werden an Effekt-Callbackfunktionen übergeben, sind Rückgabewert von <funclink>AddEffect</funclink> und lassen sich über <funclink>GetEffect</funclink> aus dem Effektnamen herausfinden.</desc>
        </param>
        <param>
          <type>string</type>
          <name>command</name>
          <desc>Aufzurufender Befehl. Es wird automatisch Fx[Effektname] vorangestellt; dies sollte nicht mit angegeben werden.</desc>
        </param>
        <param>
          <type>any</type>
          <name>...</name>
          <desc>Zusätzliche Aufrufparameter</desc>
        </param>
      </params>
    </syntax>

    <desc>Führt einen Funktionsaufruf im angegebenen Effekt durch. Der Aufruf erhält den Befehlskontext des Effektes, und die ersten beiden Aufrufparameter sind immer Zielobjekt und Effektindex. Die weiteren Parameter können frei gewählt werden.</desc>

    <remark>Für Beispiele und weitere Hinweise siehe <emlink href="script/Effects.html">Effekte-Dokumentation</emlink>.</remark>

    <related>
      <emlink href="script/Effects.html">Effekte-Dokumentation</emlink>
      <funclink>AddEffect</funclink>
      <funclink>ChangeEffect</funclink>
      <funclink>CheckEffect</funclink>
      <funclink>GetEffectCount</funclink>
      <funclink>EffectVar</funclink>
      <funclink>GetEffect</funclink>
      <funclink>RemoveEffect</funclink>
    </related>
  </func>
  <author>Sven2</author><date>März 2004</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/Sort_Mass.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>Sort_Mass</title>
    <category>Objects</category>
    <subcat>Search</subcat>
    <version>1.0 OC</version>
    <syntax><rtype>array</rtype></syntax>
    <desc>Sort criterion: Sorts the found objects by their mass. The lightest objects first.</desc>
    <remark>For additional information on the use of this function see <funclink>FindObjects</funclink>.</remark>
    <related><funclink>FindObjects</funclink></related>
  </func>
  <author>Newton</author><date>2009-07</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/CreateContents.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>CreateContents</title>
    <category>Objects</category>
    <subcat>Creation</subcat>
    <version>1.0 OC</version>
    <syntax>
      <rtype>object</rtype>
      <params>
        <param>
          <type>id</type>
          <name>id</name>
          <desc>Type of object to be created.</desc>
        </param>
        <param>
          <type>int</type>
          <name>count</name>
          <desc>Number of objects to be created, if not specified, 1 is assumed.</desc>
        </param>
      </params>
    </syntax>
    <desc>Creates an object of the specified type in the contents of another object.</desc>
    <examples>
      <example>
        <code><funclink>GetHiRank</funclink>(0)-&gt;CreateContents(Rock);</code>
        <text>The highest ranking clonk of this player receives a rock.</text>
      </example>
    </examples>
    <related>
      <funclink>CreateConstruction</funclink>
      <funclink>CreateObject</funclink>
      <funclink>RemoveObject</funclink>
    </related>
  </func>
  <author>springer</author><date>2002-04</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/ToggleBit.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>ToggleBit</title>
    <category>Arithmetics</category>
    <version>1.0 OC</version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>int</type>
          <name>old_value</name>
          <desc>Old value of the bit masc</desc>
        </param>
        <param>
          <type>int</type>
          <name>bit_number</name>
          <desc>The bit to flip</desc>
        </param>
      </params>
    </syntax>
    <desc>Returns the new bit masc with the bit at the indicated position flipped</desc>
    <related>
      <funclink>SetBit</funclink>
      <funclink>GetBit</funclink>
    </related>
  </func>
  <author>Newton</author><date>2009-07</date>
</funcs>
