=== openclonk/openclonk/docs/clonk.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY % text "a | img | emlink | funclink | em | code | strong">

<!ELEMENT funcs (func+, (author, date)+)>
  <!ELEMENT func           (title, deprecated?, category, subcat*, version, deprecated?, syntax, desc, remark*, examples?, related?)>
    <!ELEMENT title        (#PCDATA)>
    <!ELEMENT category     (#PCDATA)>
    <!ELEMENT subcat       (#PCDATA)>
    <!ELEMENT version      (#PCDATA | extversion)*>
      <!ELEMENT extversion (#PCDATA)>
    <!ELEMENT deprecated   EMPTY>
    <!ELEMENT internal     EMPTY>
    <!ELEMENT syntax       (rtype, params*)>
      <!ELEMENT rtype      (#PCDATA)>
      <!ELEMENT params     (#PCDATA | param)*>
        <!ELEMENT param    (type?, optional?, name, optional?, desc, optional?)>
          <!ELEMENT name   (#PCDATA)>
          <!ELEMENT type   (#PCDATA)>
          <!ELEMENT desc   (#PCDATA | br | ul | li | table | %text;)*>
          <!ELEMENT optional EMPTY>
    <!ELEMENT remark       (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT examples     (example+)>
      <!ELEMENT example    (code | text)*>
        <!ELEMENT code     (#PCDATA | funclink | emlink | em | strong)*>
        <!ELEMENT text     (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT related      (funclink | emlink)+>
      <!ELEMENT funclink   (#PCDATA)>
      <!ELEMENT emlink     (#PCDATA)>
        <!ATTLIST emlink href CDATA #REQUIRED>
  <!ELEMENT author         (#PCDATA)>
  <!ELEMENT date           (#PCDATA)>
<!ELEMENT doc (title, (h | text | dl | part | code | author | date | img)*)>
  <!ELEMENT part (h | text | part | code | dl)*>

<!ELEMENT br EMPTY>

<!ELEMENT table (#PCDATA | caption | rowh | row | bitmask)*>
  <!ELEMENT caption (#PCDATA)>
    <!ATTLIST caption
      id ID #IMPLIED>
  <!ELEMENT row   (#PCDATA | col)*>
    <!ATTLIST row
      id ID #IMPLIED>
  <!ELEMENT rowh  (#PCDATA | col)*>
  <!ELEMENT col   (#PCDATA | %text;)*>
    <!ATTLIST col
      colspan CDATA #IMPLIED>
  <!ELEMENT bitmask (#PCDATA)>

<!ELEMENT ul    (#PCDATA | li)*>
  <!ELEMENT li    (#PCDATA | br | %text;)*>

<!ELEMENT dl    (#PCDATA | dd | dt)*>
  <!ELEMENT dt    (#PCDATA | br | %text;)*>
    <!ATTLIST dt
      id ID #IMPLIED>
  <!ELEMENT dd    (#PCDATA | text | code)*>

<!ELEMENT em    (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

<!ELEMENT h     (#PCDATA)>
  <!ATTLIST h
    id ID #IMPLIED>

<!ELEMENT img   EMPTY>
  <!ATTLIST img
    src CDATA #REQUIRED
    width CDATA "0"
    height CDATA "0"
    id ID #IMPLIED>

<!ELEMENT a     (#PCDATA)>
  <!ATTLIST a
    href CDATA #REQUIRED>

=== openclonk/openclonk/docs/sdk/script/fn/Surrender.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>Surrender</title>
    <category>Player</category>
    <version>9.0 OC</version>
    <syntax>
      <rtype>bool</rtype>
    </syntax>
    <desc>Makes a player surrender. Returns <code>false</code> if the player was already eliminated.</desc>
    <related><funclink>EliminatePlayer</funclink></related>
  </func>
  <author>Marky</author><date>2020-06</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/SoundAt.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>SoundAt</title>
    <category>Effects</category>
    <version>4.0 OC</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>string</type>
          <name>name</name>
          <desc>Name of the sound effect (without .wav/.ogg extension). Wildcards as used by <funclink>WildcardMatch</funclink> are used.</desc>
        </param>
        <param>
          <type>int</type>
          <name>x</name>
          <desc>X-Position of the sound effect. An offset if called from object-context.</desc>
        </param>
        <param>
          <type>int</type>
          <name>y</name>
          <desc>Y-Position of the sound effect. An offset if called from object-context.</desc>
        </param>
        <param>
          <type>int</type>
          <name>volume</name>
          <desc>0-100: volume for playback of the sound. A volume value of <code>nil</code> means playback at 100.</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>player</name>
          <desc>Player number of the player for which the sound is to be played. In network games, the sound will thus not be audible for the other players. If <code>nil</code> (or not specified), the sound will be played for all players.</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>custom_falloff_distance</name>
          <desc>The further away the sound effect from the player, the more quiet it is played. By default, the sound will not be hearable anymore in a distance of 700 pixels. A custom distance can be specified here.</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>pitch</name>
          <desc>Pitch modification between -90 and 1000. Values larger than zero let the sound play the faster and at a higher pitch. The resulting speed multiplication factor is (pitch + 100) / 100.</desc>
          <optional />
        </param>
        <param>
          <type>proplist</type>
          <name>modifier</name>
          <desc>Sound modifier for special effects such as reverb or echo. See <emlink href="script/SoundModifiers.html">Sound modifiers</emlink>.</desc>
          <optional />
        </param>
	</params>
    </syntax>
    <desc>Plays a sound at the specified position. The specified sound file has to be available in the group Sound.ocg, in the active scenario file, or in any loaded object definition.</desc>
    <related><funclink>Sound</funclink></related>
    <related><funclink>Music</funclink></related>
    <related><emlink href="script/SoundModifiers.html">Sound modifiers</emlink></related>
	</func>
  <author>Sven2</author><date>2002-08</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/SetPhysical.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>SetPhysical</title>
    <category>Objects</category>
    <subcat>Status</subcat>
    <version>4.6.5.0 CP<extversion>4.9.6.0 CR</extversion></version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>string</type>
          <name>physical</name>
          <desc>Name of property to be changed.</desc>
        </param>
        <param>
          <type>int</type>
          <name>value</name>
          <desc>0-100000: new value for the property</desc>
        </param>
        <param>
          <type>int</type>
          <name>mode</name>
          <desc>
            Physical attribute change mode (symbolical constants since CR):<br/>
            <table>
              <rowh>
                <col>Constant</col>
                <col>Value</col>
                <col>Meaning</col>
              </rowh>
              <row>
                <col>PHYS_Current</col>
                <col>0</col>
                <col>The physical attributes are changed in the current mode (temporary or permanent) of the object.</col>
              </row>
              <row>
                <col>PHYS_Permanent</col>
                <col>1</col>
                <col>The physical attributes are changed in permanent mode. This modifies the info section of the associated crew object, which means that the changes will be written to the player file as well. Only player crew objects have  a permanent info section.</col>
              </row>
              <row>
                <col>PHYS_Temporary</col>
                <col>2</col>
                <col>The object will be set to temporary physical mode, and a temporary info section will be created if none exists already. Use <funclink>ResetPhysical</funclink> to reset temporary physicals to permanent mode.</col>
              </row>
              <row>
                <col>PHYS_StackTemporary</col>
                <col>3</col>
                <col>Like PHYS_Temporary, but the previous physical-value will be backed up and can be restored by calling <funclink>ResetPhysical</funclink>. Since CR.</col>
              </row>
            </table>
<br/>
          </desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>Changes the physical properties of the object. With this, the values from the Physical section of the <emlink href="definition/DefCore.html">DefCore.txt</emlink> can be permanently or temporarily adapted.</desc>
    <examples>
      <example>
        <code>protected func Activate(eater)
  {
  [$DescEatPill$]
  eater-&gt;SetPhysical(&quot;Magic&quot;, 1000000, PHYS_Temporary);
  <funclink>while</funclink>(eater-&gt;<funclink>DoMagicEnergy</funclink>(1)) ;
  <funclink>RemoveObject</funclink>();
  }</code>
        <text>Script for a magic pill: the eating clonk will temporarily gain magic energy.</text>
      </example>
      <example>
        <code>protected func FxJumpBoostStart(object trg, int num, int temporary)
  {
  trg-&gt;SetPhysical(&quot;Jump&quot;, trg-&gt;<funclink>GetPhysical</funclink>(&quot;Jump&quot;, PHYS_Current) + 10000, PHYS_StackTemporary);
  <funclink>return</funclink>(FX_OK);
  }
		
protected func FxJumpBoostStop(object trg, int num, int reason, bool tmp)
  {
  trg-&gt;<funclink>ResetPhysical</funclink>(&quot;Jump&quot;);
  <funclink>return</funclink>(FX_OK);
  }</code>
        <text>Script of an effect named JumpBoost: If created on a Clonk, it can jump higher until the effect is deleted again. Using PHYS_StackTemporary and <funclink>ResetPhysical</funclink> in this manner ensures that multiple effects written in this style can be combined without causing unwanted behaviour when one effect wears off while another remains.</text>
      </example>
    </examples>
    <related>
      <emlink href="definition/DefCore.html#SektionPhysical">DefCore.txt, [Physical]</emlink>
      <funclink>GetPhysical</funclink>
      <funclink>ResetPhysical</funclink>
      <funclink>TrainPhysical</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2003-06</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/AppendCommand.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>AppendCommand</title>
    <category>Objekte</category>
    <subcat>Commands</subcat>
    <version>4.6.5.0 CP<extversion>4.9.1.0 GWE</extversion></version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>object</type>
          <name>pObj</name>
          <desc>Objekt, dem das Kommando gegeben wird.</desc>
        </param>
        <param>
          <type>string</type>
          <name>szCommand</name>
          <desc>Kommandoname (als String). Siehe untere Tabelle </desc>
        </param>
        <param>
          <type>object</type>
          <name>pTarget</name>
          <optional />
          <desc>Zielobjekt für Aktion</desc>
        </param>
        <param>
          <type>int</type>
          <name>iX</name>
          <optional />
          <desc>X-Zielkoordinate</desc>
        </param>
        <param>
          <type>int</type>
          <name>iY</name>
          <optional />
          <desc>Y-Zielkoordinate</desc>
        </param>
        <param>
          <type>object</type>
          <name>pTarget2</name>
          <optional />
          <desc>zweites Zielobjekt</desc>
        </param>
        <param>
          <type>int</type>
          <name>iInterval</name>
          <optional />
          <desc>Zeit (in Ticks/Frames), bis das Kommando abgebrochen wird</desc>
        </param>
        <param>
          <type>any</type>
          <name>Data</name>
          <optional />
          <desc>zusätzliche Daten zur Aktion</desc>
        </param>
        <param>
          <type>int</type>
          <name>iRetries</name>
          <optional />
          <desc>Anzahl der Wiederholungen (wenn das Kommando fehlschlägt), bis das Kommando abgebrochen wird.</desc>
        </param>
        <param>
          <type>int</type>
          <name>iBaseMode</name>
          <optional />
          <desc>Befehlsstapelmodus. Werte siehe <funclink>AddCommand</funclink>.</desc>
        </param>
      </params>
    </syntax>

    <desc>Fügt ein Kommando der Kommandoliste eines Objekts am Ende hinzu. Das Objekt wird also das zuerst gegebene Kommando ausführen und sich danach automatisch dem mit AppendCommand hinzugefügten widmen.<br />
          Für Kommando-Beschreibungen siehe <funclink>SetCommand</funclink><br/>
          Bemerkung: Mit AppendCommand hinzugefügte Befehle werden nicht an gesteuerte Fahrzeuge weitergeleitet (siehe VehicleControl)</desc>

    <examples>
      <example>
        <code>var base = <funclink>FindBase</funclink>();
<funclink>SetCommand</funclink>(<funclink>this</funclink>(), "MoveTo", base);
AppendCommand(<funclink>this</funclink>(), "Throw", 0, <funclink>GetX</funclink>(base), <funclink>GetY</funclink>(base));</code>
        <text>
Gibt dem Clonk den Befehl, zuerst zu der ersten (gefundenen) Basis zu laufen, und dann das erste Objekt, das er trägt, auf diese zu werfen.<br />
        </text>
      </example>
    </examples>
    <related>
      <funclink>SetCommand</funclink>
      <funclink>GetCommand</funclink>
      <funclink>AddCommand</funclink>
      <funclink>FinishCommand</funclink>
    </related>
  </func>
  <author>PeterW</author><date>November 2001</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/_inherited.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>_inherited</title>
    <category>Script</category>
    <version>4.9.1.0 GWE</version>
    <syntax>
      <rtype>any</rtype>
      <params>
        <param><type>any</type><name>...</name><desc>Aufrufparameter</desc></param>
      </params>
    </syntax>
    <desc>Ruft die überladene Funktion auf. Funktionen überladen sich, wenn sie beide den gleichen Namen haben. Die Funktion ist im Gegensatz zu <funclink>inherited</funclink> außerdem failsafe. Das heißt, dass es zu keinem Fehler führt, wenn die Ursprungsfunktion gar nicht existiert.</desc>
    <examples>
      <example>

<code>

#appendto Clonk

func Initialize()
{
  <funclink>CreateContents</funclink>(Firestone);
  <funclink>return</funclink> _inherited(...);
}</code>

        <text>Gibt jedem Clonk zu Beginn einen Feuerstein.</text>
      </example>
    </examples>
    <related>
      <funclink>inherited</funclink>
    </related>
  </func>
  <author>Sven2</author><date>November 2001</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/SetLength.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
	<func>
		<title>SetLength</title>
		<category>Script</category><subcat>Strings</subcat>
		<version>4.9.6.0 CR</version>
		<syntax>
			<rtype>int</rtype>
			<params>
				<param><type>array</type><name>resize</name><desc>Array, dessen Länge verändert werden soll</desc></param>
				<param><type>int</type><name>size</name><desc>Neue Länge des Feldes</desc></param>
			</params>
		</syntax>
		<desc>Verändert die Länge eines Arrays auf den angegebenen Wert. Überzählige Elemente werden dabei gegebenenfalls gelöscht.</desc>
		<related>
			<funclink>GetLength</funclink>
			<funclink>CreateArray</funclink>
		</related>
	</func>
	<author>Clonkonaut</author><date>Juli 2006</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/VIS_Enemies.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE funcs SYSTEM "../../../clonk.dtd">
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
	<func>
		<title>VIS_Enemies</title>
		<category>Objekte</category><subcat>Sichtbarkeit</subcat>
		<version>4.9.1.0 GWE</version>
		<syntax>
			<rtype>int</rtype>
		</syntax>
		<desc>Konstante für <funclink>GetVisibility</funclink>/<funclink>SetVisibility</funclink>. Das Objekt ist für alle Feinde des Besitzers sichtbar.</desc>
		<remark>Dieser Wert ist als Engine-Konstante definiert. Die Funktionsklammern können daher optional weggelassen werden.</remark>
		<examples>
			<example>

<code>for(var obj in FindObjects(Find_Or(Find_ID(BANR),Find_ID(BANP)))) SetVisibility(VIS_Enemies | VIS_God, obj);
</code>

				<text>Alle Banner sind nur noch für die jeweiligen Gegner der besitzenden Spieler sichtbar.</text>
			</example>
		</examples>
		<related>
			<funclink>GetVisibility</funclink>
			<funclink>SetVisibility</funclink>
			<funclink>VIS_All</funclink>
			<funclink>VIS_None</funclink>
			<funclink>VIS_Owner</funclink>
			<funclink>VIS_Allies</funclink>
			<funclink>VIS_God</funclink>
			<funclink>VIS_Local</funclink>
		</related>
	</func>
	<author>Sven2</author><date>November 2001</date>
</funcs>

=== openclonk/openclonk/docs/sdk/script/fn/GetPlrKnowledge.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>GetPlrKnowledge</title>
    <category>Player</category>
    <version>5.1 OC</version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>int</type>
          <name>player</name>
          <desc>Player whose construction plans you want to determine.</desc>
        </param>
        <param>
          <type>id</type>
          <name>id</name>
          <desc>If specified, the function returns true, if the player has the construction plan of the specified object.</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>index</name>
          <desc>Specify only if id is not 0.</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>category</name>
          <desc>Specify only if id is not 0.</desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>With id specified the function returns true if the player has the construction plan of the specified object. In this case index and category are ignored. If id is 0, the function returns the indicated construction plan of the specified category.</desc>
    <examples>
      <example>
        <code><funclink>if</funclink>(GetPlrKnowledge(0,WindGenerator))
	<funclink>Log</funclink>(&quot;Player %s can construct a %s&quot;,<funclink>GetPlayerName</funclink>(0),WindGenerator-&gt;<funclink>GetName</funclink>());</code>
        <text>Displays a message if the first player has the construction plan for wind generators.</text>
        <code>var def = GetPlrKnowledge( 0,nil,4,<funclink>C4D_Structure</funclink>);
<funclink>Log</funclink>(&quot;The fifth construction plan of the first player is for ID "%i"&quot;,def);</code>
        <text />
      </example>
    </examples>
    <related>
      <funclink>SetPlrKnowledge</funclink>
      <funclink>C4D_All</funclink>
      <funclink>C4D_Goal</funclink>
      <funclink>C4D_Living</funclink>
      <funclink>C4D_Object</funclink>
      <funclink>C4D_Rule</funclink>
      <funclink>C4D_StaticBack</funclink>
      <funclink>C4D_Structure</funclink>
      <funclink>C4D_Vehicle</funclink>
    </related>
  </func>
  <author>GÃ¼nther</author><date>2002-02</date>
</funcs>
